[package]
name = "test-parachain-halt"
description = "Test parachain which executes forever"
build = "build.rs"
publish = false
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]

[build-dependencies]
substrate-wasm-builder = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
rustversion = "1.0.6"

[features]
default = [ "std" ]
std = []
