[package]
name = "pallet-xcm-benchmarks"
authors.workspace = true
edition.workspace = true
license.workspace = true
version = "1.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }
frame-support ={  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
frame-system = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
sp-runtime = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
sp-std ={  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
sp-io ={  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
xcm-executor = { package = "staging-xcm-executor", path = "../xcm-executor", default-features = false }
frame-benchmarking ={  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
xcm = { package = "staging-xcm", path = "..", default-features = false }
xcm-builder = { package = "staging-xcm-builder", path = "../xcm-builder", default-features = false }
log = "0.4.17"

[dev-dependencies]
pallet-balances = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
pallet-assets = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
sp-core = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
sp-tracing = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
xcm = { package = "staging-xcm", path = ".." }
# temp
pallet-xcm = { path = "../pallet-xcm" }
saitama-runtime-common = { path = "../../runtime/common" }
saitama-primitives = { path = "../../primitives" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"xcm-builder/std",
	"xcm-executor/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-assets/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"saitama-primitives/runtime-benchmarks",
	"saitama-runtime-common/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
]
