[package]
name = "saitama-node-core-pvf-execute-worker"
description = "SaitaChain crate that contains the logic for executing PVFs. Used by the SaitaChain-execute-worker binary."
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cpu-time = "1.0.0"
futures = "0.3.21"
gum = { package = "tracing-gum", path = "../../../gum" }
rayon = "1.5.1"
tokio = { version = "1.24.2", features = ["fs", "process"] }

parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }

saitama-node-core-pvf-common = { path = "../common" }
saitachain-parachain-primitives = { path = "../../../../parachain" }
saitama-primitives = { path = "../../../../primitives" }

sp-core = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sp-maybe-compressed-blob = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sp-tracing = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }

[features]
builder = []
