[package]
name = "saitama-overseer"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
client = { package = "sc-client-api",git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sp-api = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
futures = "0.3.21"
futures-timer = "3.0.2"
parking_lot = "0.12.0"
saitama-node-network-protocol = { path = "../network/protocol" }
saitama-node-primitives = { path = "../primitives" }
saitama-node-subsystem-types = { path = "../subsystem-types" }
saitama-node-metrics = { path = "../metrics" }
saitama-primitives = { path = "../../primitives" }
orchestra = "0.0.5"
gum = { package = "tracing-gum", path = "../gum" }
schnellru = "0.2.1"
sp-core = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
async-trait = "0.1.57"
tikv-jemalloc-ctl = { version = "0.5.0", optional = true }

[dev-dependencies]
metered = { package = "prioritized-metered-channel", version = "0.2.0" }

sp-core = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
futures = { version = "0.3.21", features = ["thread-pool"] }
femme = "2.2.1"
assert_matches = "1.4.0"
test-helpers = { package = "saitama-primitives-test-helpers", path = "../../primitives/test-helpers" }

[target.'cfg(target_os = "linux")'.dependencies]
tikv-jemalloc-ctl = "0.5.0"

[features]
default = []
expand = [ "orchestra/expand" ]
dotgraph = [ "orchestra/dotgraph" ]
jemalloc-allocator = [ "dep:tikv-jemalloc-ctl" ]
