[package]
name = "saitama-node-core-pvf-prepare-worker"
description = "SaitaChain crate that contains the logic for preparing PVFs. Used by the SaitaChain-prepare-worker binary."
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
futures = "0.3.21"
gum = { package = "tracing-gum", path = "../../../gum" }
libc = "0.2.139"
rayon = "1.5.1"
tikv-jemalloc-ctl = { version = "0.5.0", optional = true }
tokio = { version = "1.24.2", features = ["fs", "process"] }

parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }

saitama-node-core-pvf-common = { path = "../common" }
saitachain-parachain-primitives = { path = "../../../../parachain" }
saitama-primitives = { path = "../../../../primitives" }

sc-executor = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sc-executor-common = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sc-executor-wasmtime = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sp-io = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sp-maybe-compressed-blob = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sp-tracing = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }

[target.'cfg(target_os = "linux")'.dependencies]
tikv-jemalloc-ctl = "0.5.0"

[features]
builder = []
jemalloc-allocator = [
	"dep:tikv-jemalloc-ctl",
	"saitama-node-core-pvf-common/jemalloc-allocator",
]
