[[bin]]
name = "staging-staking-miner"
path = "src/main.rs"

[package]
name = "staging-staking-miner"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1" }
clap = { version = "4.4.2", features = ["derive", "env"] }
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
jsonrpsee = { version = "0.16.2", features = ["ws-client", "macros"] }
log = "0.4.17"
paste = "1.0.7"
serde = "1.0.188"
serde_json = "1.0"
thiserror = "1.0.48"
tokio = { version = "1.24.2", features = ["macros", "rt-multi-thread", "sync"] }
remote-externalities = { package = "frame-remote-externalities" ,   git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev" } 
signal-hook-tokio = { version = "0.3", features = ["futures-v0_3"] }
sp-core =  { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev" }
sp-version = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev" }
sp-state-machine =  { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev" }
sp-runtime = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev" }
sp-npos-elections = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev" }
sc-transaction-pool-api =  { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev" }

frame-system =  { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev" }
frame-support =  { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev" }
frame-election-provider-support =  { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev" }
pallet-election-provider-multi-phase = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev" }
pallet-staking = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev" }
pallet-balances =  { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev" }
pallet-transaction-payment =  { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev" }

core-primitives = { package = "saitama-core-primitives", path = "../../core-primitives" }

runtime-common = { package = "saitama-runtime-common", path = "../../runtime/common" }
saitama-runtime = { path = "../../runtime/saitachain" }
exitcode = "1.1"

sub-tokens = { git = "https://github.com/paritytech/substrate-debug-kit", branch = "master" }
signal-hook = "0.3"
futures-util = "0.3"

[dev-dependencies]
assert_cmd = "2.0.4"
