[package]
name = "saitama-node-core-parachains-inherent"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
futures = "0.3.21"
futures-timer = "3.0.2"
gum = { package = "tracing-gum", path = "../../gum" }
thiserror = "1.0.48"
async-trait = "0.1.57"
saitama-node-subsystem = { path = "../../subsystem" }
saitama-overseer = { path = "../../overseer" }
saitama-primitives = { path = "../../../primitives" }
sp-blockchain = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sp-inherents = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
