[package]
name = "saitama-dispute-distribution"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
futures = "0.3.21"
futures-timer = "3.0.2"
gum = { package = "tracing-gum", path = "../../gum" }
derive_more = "0.99.17"
parity-scale-codec = { version = "3.6.1", features = ["std"] }
saitama-primitives = { path = "../../../primitives" }
saitama-erasure-coding = { path = "../../../erasure-coding" }
saitama-node-subsystem = { path = "../../subsystem" }
saitama-node-network-protocol = { path = "../protocol" }
saitama-node-subsystem-util = { path = "../../subsystem-util" }
saitama-node-primitives = { path = "../../primitives" }
sc-network = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sp-application-crypto = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sp-keystore = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev"}
thiserror = "1.0.48"
fatality = "0.0.6"
schnellru = "0.2.1"
indexmap = "1.9.1"

[dev-dependencies]
async-channel = "1.8.0"
async-trait = "0.1.57"
saitama-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-keyring = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev"}
sp-tracing = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sc-keystore = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
futures-timer = "3.0.2"
assert_matches = "1.4.0"
lazy_static = "1.4.0"
saitama-primitives-test-helpers = { path = "../../../primitives/test-helpers" }
