[package]
name = "saitachain-test-runtime"
build = "build.rs"
publish = false
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bitvec = { version = "1.0.0", default-features = false, features = ["alloc"] }
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }
log = { version = "0.4.17", default-features = false }
rustc-hex = { version = "2.1.0", default-features = false }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.188", default-features = false }
serde_derive = { version = "1.0.117", optional = true }
smallvec = "1.8.0"

authority-discovery-primitives = { package = "sp-authority-discovery",  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false  }
babe-primitives = { package = "sp-consensus-babe",  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false  }
beefy-primitives = { package = "sp-consensus-beefy", git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false  }
sp-api = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
inherents = { package = "sp-inherents", git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
offchain-primitives = { package = "sp-offchain",  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false  }
sp-std ={  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
sp-io = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false  }
sp-runtime = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false  }
sp-staking = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false  }
sp-core = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
sp-mmr-primitives = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
sp-session = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
sp-version = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
frame-election-provider-support ={  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
tx-pool-api = { package = "sp-transaction-pool",  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
block-builder-api = { package = "sp-block-builder", git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false  }

pallet-authority-discovery = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
pallet-authorship ={  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
pallet-babe ={  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
pallet-balances = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
pallet-transaction-payment = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
pallet-transaction-payment-rpc-runtime-api = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
frame-executive = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
pallet-grandpa = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
pallet-indices = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
pallet-offences = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
pallet-session = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
frame-support = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
pallet-staking = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
frame-system = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
frame-system-rpc-runtime-api = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev", default-features = false }
test-runtime-constants = { package = "test-runtime-constants", path = "constants", default-features = false }
pallet-timestamp = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false}
pallet-vesting = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false}

runtime-common = { package = "saitama-runtime-common", path = "../common", default-features = false }
primitives = { package = "saitama-primitives", path = "../../primitives", default-features = false }
pallet-xcm = { path = "../../xcm/pallet-xcm", default-features = false }
saitachain-parachain-primitives = { path = "../../parachain", default-features = false }
saitama-runtime-parachains = { path = "../parachains", default-features = false }
xcm-builder = { package = "staging-xcm-builder", path = "../../xcm/xcm-builder", default-features = false }
xcm-executor = { package = "staging-xcm-executor", path = "../../xcm/xcm-executor", default-features = false }
xcm = { package = "staging-xcm", path = "../../xcm", default-features = false }

[dev-dependencies]
hex-literal = "0.4.1"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
keyring = { package = "sp-keyring", git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sp-trie = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
serde_json = "1.0.96"

[build-dependencies]
substrate-wasm-builder = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev"}

[features]
default = [ "std" ]
no_std = []
only-staking = []
runtime-metrics = [
	"saitama-runtime-parachains/runtime-metrics",
	"sp-io/with-tracing",
]

std = [
	"authority-discovery-primitives/std",
	"babe-primitives/std",
	"beefy-primitives/std",
	"bitvec/std",
	"block-builder-api/std",
	"frame-election-provider-support/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"inherents/std",
	"log/std",
	"offchain-primitives/std",
	"pallet-authority-discovery/std",
	"pallet-authorship/std",
	"pallet-babe/std",
	"pallet-balances/std",
	"pallet-grandpa/std",
	"pallet-indices/std",
	"pallet-offences/std",
	"pallet-session/std",
	"pallet-staking/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"pallet-vesting/std",
	"pallet-xcm/std",
	"parity-scale-codec/std",
	"saitachain-parachain-primitives/std",
	"saitama-runtime-parachains/std",
	"primitives/std",
	"runtime-common/std",
	"rustc-hex/std",
	"scale-info/std",
	"serde/std",
	"serde_derive",
	"sp-api/std",
	"sp-core/std",
	"sp-io/std",
	"sp-mmr-primitives/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-staking/std",
	"sp-std/std",
	"sp-version/std",
	"test-runtime-constants/std",
	"tx-pool-api/std",
	"xcm-builder/std",
	"xcm-executor/std",
	"xcm/std",
]

runtime-benchmarks = [
	"frame-election-provider-support/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-babe/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-grandpa/runtime-benchmarks",
	"pallet-indices/runtime-benchmarks",
	"pallet-offences/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-vesting/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"saitachain-parachain-primitives/runtime-benchmarks",
	"saitama-runtime-parachains/runtime-benchmarks",
	"primitives/runtime-benchmarks",
	"runtime-common/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-staking/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
]
