[package]
name = "saitama-node-jaeger"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "SaitaChain Jaeger primitives, but equally useful for Grafana/Tempo"

[dependencies]
mick-jaeger = "0.1.8"
lazy_static = "1.4"
parking_lot = "0.12.0"
saitama-primitives = { path = "../../primitives" }
saitama-node-primitives = { path = "../primitives" }
sc-network = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sp-core = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
thiserror = "1.0.48"
tokio = "1.24.2"
log = "0.4.17"
parity-scale-codec = { version = "3.6.1", default-features = false }
