[package]
name = "saitama-node-core-pvf"
description = "SaitaChain crate that implements the PVF validation host. Responsible for coordinating preparation and execution of PVFs."
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "puppet_worker"
path = "bin/puppet_worker.rs"
required-features = ["test-utils"]

[dependencies]
always-assert = "0.1"
futures = "0.3.21"
futures-timer = "3.0.2"
gum = { package = "tracing-gum", path = "../../gum" }
libc = "0.2.139"
pin-project = "1.0.9"
rand = "0.8.5"
slotmap = "1.0"
tempfile = "3.3.0"
tokio = { version = "1.24.2", features = ["fs", "process"] }

parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }

saitachain-parachain-primitives = { path = "../../../parachain" }
saitama-core-primitives = { path = "../../../core-primitives" }
saitama-node-core-pvf-common = { path = "common" }
saitama-node-metrics = { path = "../../metrics" }
saitama-node-primitives = { path = "../../primitives" }
saitama-primitives = { path = "../../../primitives" }

sp-core = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sp-wasm-interface = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sp-maybe-compressed-blob = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sp-tracing = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev", optional = true }
saitama-node-core-pvf-prepare-worker = { path = "prepare-worker", optional = true }
saitama-node-core-pvf-execute-worker = { path = "execute-worker", optional = true }

[build-dependencies]
substrate-build-script-utils = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }

[dev-dependencies]
assert_matches = "1.4.0"
hex-literal = "0.3.4"
saitama-node-core-pvf-common = { path = "common", features = ["test-utils"] }
# For the puppet worker, depend on ourselves with the test-utils feature.
saitama-node-core-pvf = { path = ".", features = ["test-utils"] }

adder = { package = "test-parachain-adder", path = "../../../parachain/test-parachains/adder" }
halt = { package = "test-parachain-halt", path = "../../../parachain/test-parachains/halt" }

[features]
ci-only-tests = []
jemalloc-allocator = [ "saitama-node-core-pvf-common/jemalloc-allocator" ]
# This feature is used to export test code to other crates without putting it in the production build.
# This is also used by the `puppet_worker` binary.
test-utils = [
	"saitama-node-core-pvf-execute-worker",
	"saitama-node-core-pvf-prepare-worker",
	"sp-tracing",
]
