[package]
name = "saitama-node-metrics"
description = "Subsystem metric helpers"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
futures = "0.3.21"
futures-timer = "3.0.2"
gum = { package = "tracing-gum", path = "../gum" }

metered = { package = "prioritized-metered-channel", version = "0.2.0" }

# Both `sc-service` and `sc-cli` are required by runtime metrics `logger_hook()`.
sc-service = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev"}
sc-cli = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }

substrate-prometheus-endpoint = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sc-tracing = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
codec = { package = "parity-scale-codec", version = "3.6.1" }
primitives = { package = "saitama-primitives", path = "../../primitives" }
bs58 = { version = "0.5.0", features = ["alloc"] }
log = "0.4.17"

[dev-dependencies]
assert_cmd = "2.0.4"
tempfile = "3.2.0"
hyper = { version = "0.14.20", default-features = false, features = ["http1", "tcp"] }
tokio = "1.24.2"
saitama-test-service = { path = "../test/service", features=["runtime-metrics"]}
substrate-test-utils = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sc-service = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev"}
sp-keyring = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
prometheus-parse = {version = "0.2.2"}

[features]
default = []
runtime-metrics = []
runtime-benchmarks = [
	"saitama-test-service/runtime-benchmarks",
	"primitives/runtime-benchmarks",
	"sc-service/runtime-benchmarks",
]
