[package]
name = "saitama-runtime-constants"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
smallvec = "1.8.0"

frame-support = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev", default-features = false }
primitives = { package = "saitama-primitives", path = "../../../primitives", default-features = false }
runtime-common = { package = "saitama-runtime-common", path = "../../common", default-features = false }
sp-runtime = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev", default-features = false }
sp-weights ={git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev", default-features = false }
sp-core = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev", default-features = false }

[features]
default = [ "std" ]
std = [
	"frame-support/std",
	"primitives/std",
	"runtime-common/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-weights/std",
]
