[package]
name = "test-parachain-adder"
description = "Test parachain which adds to a number as its state transition"
build = "build.rs"
edition.workspace = true
license.workspace = true
version = "1.0.0"
authors.workspace = true
publish = false

[dependencies]
parachain = { package = "saitachain-parachain-primitives", path = "../..", default-features = false, features = [ "wasm-api" ] }
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }
sp-std = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev", default-features = false }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
dlmalloc = { version = "0.2.4", features = [ "global" ] }

# We need to make sure the global allocator is disabled until we have support of full substrate externalities
sp-io = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev", default-features = false, features = [ "disable_allocator" ] }

[build-dependencies]
substrate-wasm-builder = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }

[features]
default = [ "std" ]
std = [ "parachain/std", "sp-io/std", "sp-std/std" ]
