[package]
name = "saitama-node-core-av-store"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
futures = "0.3.21"
futures-timer = "3.0.2"
kvdb = "0.13.0"
thiserror = "1.0.48"
gum = { package = "tracing-gum", path = "../../gum" }
bitvec = "1.0.0"

parity-scale-codec = { version = "3.6.1", features = ["derive"] }
erasure = { package = "saitama-erasure-coding", path = "../../../erasure-coding" }
saitama-node-subsystem = { path = "../../subsystem" }
saitama-node-subsystem-util = { path = "../../subsystem-util" }
saitama-overseer = { path = "../../overseer" }
saitama-primitives = { path = "../../../primitives" }
saitama-node-primitives = { path = "../../primitives" }
sp-consensus = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev", default-features = false }
saitama-node-jaeger = { path = "../../jaeger" }

[dev-dependencies]
log = "0.4.17"
env_logger = "0.9.0"
assert_matches = "1.4.0"
kvdb-memorydb = "0.13.0"

sp-core = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
saitama-node-subsystem-util = { path = "../../subsystem-util" }
saitama-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-keyring = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
parking_lot = "0.12.0"
test-helpers = { package = "saitama-primitives-test-helpers", path = "../../../primitives/test-helpers" }
