[package]
name = "saitama-runtime-parachains"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
impl-trait-for-tuples = "0.2.2"
bitvec = { version = "1.0.0", default-features = false, features = ["alloc"] }
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive", "max-encoded-len"] }
log = { version = "0.4.17", default-features = false }
rustc-hex = { version = "2.1.0", default-features = false }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.188", default-features = false, features = ["derive", "alloc"] }
derive_more = "0.99.17"
bitflags = "1.3.2"

sp-api ={  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev", default-features = false }
inherents = { package = "sp-inherents",  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev", default-features = false }
sp-std = { package = "sp-std", git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev", default-features = false }
sp-io = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev", default-features = false }
sp-runtime = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev", default-features = false,features=["serde"] }
sp-session = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev", default-features = false }
sp-staking = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev", default-features = false, features=["serde"] }
sp-core = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev", default-features = false, features=["serde"] }
sp-keystore = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev", optional = true }
sp-application-crypto = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev", default-features = false, optional = true }
sp-tracing = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev", default-features = false, optional = true }

pallet-authority-discovery = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev", default-features = false }
pallet-authorship = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev", default-features = false }
pallet-balances = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev", default-features = false }
pallet-babe = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev", default-features = false }
pallet-message-queue = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev", default-features = false }
pallet-session = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev", default-features = false }
pallet-staking = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev", default-features = false }
pallet-timestamp = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev", default-features = false }
pallet-vesting = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev", default-features = false }
frame-benchmarking = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev", default-features = false, optional = true }
frame-support = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev", default-features = false}
frame-system = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev", default-features = false }

xcm = { package = "staging-xcm", path = "../../xcm", default-features = false }
xcm-executor = { package = "staging-xcm-executor", path = "../../xcm/xcm-executor", default-features = false }
primitives = { package = "saitama-primitives", path = "../../primitives", default-features = false }

rand = { version = "0.8.5", default-features = false }
rand_chacha = { version = "0.3.1", default-features = false }
static_assertions = { version = "1.1.0", optional = true }
saitachain-parachain-primitives = { path = "../../parachain", default-features = false }
saitama-runtime-metrics = { path = "../metrics", default-features = false}

[dev-dependencies]
futures = "0.3.21"
hex-literal = "0.4.1"
keyring = { package = "sp-keyring", git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev"}
frame-support-test = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev"}
sc-keystore = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev" }
test-helpers = { package = "saitama-primitives-test-helpers", path = "../../primitives/test-helpers" }
sp-tracing = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev" }
thousands = "0.2.0"
assert_matches = "1"
serde_json = "1.0.96"

[features]
default = [ "std" ]
no_std = []
std = [
	"bitvec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"inherents/std",
	"log/std",
	"pallet-authority-discovery/std",
	"pallet-authorship/std",
	"pallet-babe/std",
	"pallet-balances/std",
	"pallet-message-queue/std",
	"pallet-session/std",
	"pallet-staking/std",
	"pallet-timestamp/std",
	"pallet-vesting/std",
	"parity-scale-codec/std",
	"saitachain-parachain-primitives/std",
	"saitama-runtime-metrics/std",
	"primitives/std",
	"rustc-hex/std",
	"scale-info/std",
	"serde/std",
	"sp-api/std",
	"sp-application-crypto?/std",
	"sp-core/std",
	"sp-io/std",
	"sp-keystore",
	"sp-runtime/std",
	"sp-session/std",
	"sp-staking/std",
	"sp-std/std",
	"xcm-executor/std",
	"xcm/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-babe/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-message-queue/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-vesting/runtime-benchmarks",
	"saitachain-parachain-primitives/runtime-benchmarks",
	"primitives/runtime-benchmarks",
	"sp-application-crypto",
	"sp-runtime/runtime-benchmarks",
	"sp-staking/runtime-benchmarks",
	"static_assertions",
	"xcm-executor/runtime-benchmarks",
]
try-runtime = [
	"frame-support-test/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-authority-discovery/try-runtime",
	"pallet-authorship/try-runtime",
	"pallet-babe/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-message-queue/try-runtime",
	"pallet-session/try-runtime",
	"pallet-staking/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-vesting/try-runtime",
	"sp-runtime/try-runtime",
]
runtime-metrics = [
	"saitama-runtime-metrics/runtime-metrics",
	"sp-tracing/with-tracing",
]
