[package]
name = "pallet-xcm"
authors.workspace = true
edition.workspace = true
license.workspace = true
version = "1.0.0"


[dependencies]
bounded-collections = { version = "0.1.8", default-features = false }
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.188", optional = true, features = ["derive"] }
log = { version = "0.4.17"}

frame-benchmarking = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev", default-features = false, optional = true }
frame-support = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
frame-system =  {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
sp-core = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
sp-io = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev"}
sp-runtime =  {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev" }
sp-std = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }

xcm = { package = "staging-xcm", path = "..", default-features = false }
xcm-executor = { package = "staging-xcm-executor", path = "../xcm-executor", default-features = false }

[dev-dependencies]
pallet-balances = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev" }
saitama-runtime-parachains = { path = "../../runtime/parachains" }
saitachain-parachain-primitives = { path = "../../parachain" }
xcm-builder = { package = "staging-xcm-builder", path = "../xcm-builder" }

[features]
default = [ "std" ]
# Enable `VersionedMigration` for the migrations using the experimental feature.
experimental = [ "frame-support/experimental" ]
std = [
	"bounded-collections/std",
	"codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"serde",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"xcm-executor/std",
	"xcm/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"saitachain-parachain-primitives/runtime-benchmarks",
	"saitama-runtime-parachains/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-balances/try-runtime",
	"saitama-runtime-parachains/try-runtime",
	"sp-runtime/try-runtime",
]
