[package]
name = "saitama-test-malus"
description = "Misbehaving nodes for local testnets, system and Simnet tests."
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
publish = false

[[bin]]
name = "malus"
path = "src/malus.rs"

# Use artifact dependencies once stable.
# See https://github.com/rust-lang/cargo/issues/9096.
[[bin]]
name = "SaitaChain-execute-worker"
path = "../../src/bin/execute-worker.rs"
# Prevent rustdoc error. Already documented from top-level Cargo.toml.
doc = false
[[bin]]
name = "SaitaChain-prepare-worker"
path = "../../src/bin/prepare-worker.rs"
# Prevent rustdoc error. Already documented from top-level Cargo.toml.
doc = false

[dependencies]
saitama-cli = { path = "../../cli", features = [ "malus",  "saitachain-native" ] }
saitama-node-subsystem = { path = "../subsystem" }
saitama-node-subsystem-util = { path = "../subsystem-util" }
saitama-node-subsystem-types = { path = "../subsystem-types" }
saitama-node-core-dispute-coordinator = { path = "../core/dispute-coordinator" }
saitama-node-core-candidate-validation = { path = "../core/candidate-validation" }
saitama-node-core-backing = { path = "../core/backing" }
saitama-node-primitives = { path = "../primitives" }
saitama-primitives = { path = "../../primitives" }
color-eyre = { version = "0.6.1", default-features = false }
assert_matches = "1.5"
async-trait = "0.1.57"
sp-keystore = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sp-core = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev"}
clap = { version = "4.4.2", features = ["derive"] }
futures = "0.3.21"
futures-timer = "3.0.2"
gum = { package = "tracing-gum", path = "../gum" }
erasure = { package = "saitama-erasure-coding", path = "../../erasure-coding" }
rand = "0.8.5"

# Required for worker binaries to build.
saitama-node-core-pvf-common = { path = "../core/pvf/common", features = ["test-utils"] }
saitama-node-core-pvf-execute-worker = { path = "../core/pvf/execute-worker" }
saitama-node-core-pvf-prepare-worker = { path = "../core/pvf/prepare-worker" }

[dev-dependencies]
saitama-node-subsystem-test-helpers = { path = "../subsystem-test-helpers" }
sp-core = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
futures = { version = "0.3.21", features = ["thread-pool"] }

[build-dependencies]
substrate-build-script-utils = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }

[features]
default = []
fast-runtime = [ "saitama-cli/fast-runtime" ]
