[package]
name = "staging-xcm-builder"
description = "Tools & types for building with XCM and its executor."
authors.workspace = true
edition.workspace = true
license.workspace = true
version = "1.0.0"

[dependencies]
impl-trait-for-tuples = "0.2.1"
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }
xcm = { package = "staging-xcm", path = "..", default-features = false }
xcm-executor = { package = "staging-xcm-executor", path = "../xcm-executor", default-features = false }
sp-std ={  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
sp-arithmetic = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
sp-io = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
sp-runtime = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
sp-weights = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
frame-support = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
frame-system ={  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
pallet-transaction-payment ={  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
log = { version = "0.4.17", default-features = false }

# SaitaChain dependencies
saitachain-parachain-primitives = { path = "../../parachain",default-features = false }

[dev-dependencies]
primitive-types = "0.12.1"
pallet-balances ={  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
pallet-xcm = { path = "../pallet-xcm" }
pallet-salary = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
pallet-assets = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev",default-features = false }
primitives = { package = "saitama-primitives", path = "../../primitives" }
saitama-runtime-parachains = { path = "../../runtime/parachains" }
assert_matches = "1.5.0"
saitachain-test-runtime = { path = "../../runtime/test-runtime" }

[features]
default = [ "std" ]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-assets/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-salary/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"saitachain-parachain-primitives/runtime-benchmarks",
	"saitama-runtime-parachains/runtime-benchmarks",
	"saitachain-test-runtime/runtime-benchmarks",
	"primitives/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
]
std = [
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"pallet-transaction-payment/std",
	"parity-scale-codec/std",
	"saitachain-parachain-primitives/std",
	"scale-info/std",
	"sp-arithmetic/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-weights/std",
	"xcm-executor/std",
	"xcm/std",
]
