[package]
name = "saitama-statement-distribution"
description = "Statement Distribution Subsystem"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
futures = "0.3.21"
futures-timer = "3.0.2"
gum = { package = "tracing-gum", path = "../../gum" }
saitama-primitives = { path = "../../../primitives" }
sp-staking = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev", default-features = false }
sp-keystore = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
saitama-node-subsystem = { path = "../../subsystem" }
saitama-node-primitives = { path = "../../primitives" }
saitama-node-subsystem-util = { path = "../../subsystem-util" }
saitama-node-subsystem-types = { path = "../../subsystem-types" }
saitama-node-network-protocol = { path = "../protocol" }
arrayvec = "0.7.4"
indexmap = "1.9.1"
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }
thiserror = "1.0.48"
fatality = "0.0.6"
bitvec = "1"

[dev-dependencies]
async-channel = "1.8.0"
assert_matches = "1.4.0"
saitama-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-authority-discovery = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sp-keyring = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sp-core = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sp-application-crypto = {git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sp-keystore = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sp-tracing = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sc-keystore = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sc-network = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
futures-timer = "3.0.2"
saitama-primitives-test-helpers = { path = "../../../primitives/test-helpers" }
rand_chacha = "0.3"
