[package]
name = "saitama-node-core-chain-api"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
futures = "0.3.21"
gum = { package = "tracing-gum", path = "../../gum" }
sp-blockchain = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
saitama-primitives = { path = "../../../primitives" }
saitama-node-metrics = { path = "../../metrics" }
saitama-node-subsystem = { path = "../../subsystem" }
sc-client-api = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sc-consensus-babe = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }

[dev-dependencies]
futures = { version = "0.3.21", features = ["thread-pool"] }
maplit = "1.0.2"
parity-scale-codec = "3.6.1"
saitama-node-primitives = { path = "../../primitives" }
saitama-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-core = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
