[package]
name = "slot-range-helper"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
paste = "1.0"
enumn = "0.1.12"
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }
sp-std = { package = "sp-std",  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev", default-features = false }
sp-runtime = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev", default-features = false }

[features]
default = [ "std" ]
std = [ "parity-scale-codec/std", "sp-runtime/std", "sp-std/std" ]
