[package]
name = "pallet-evm-precompile-bw6761"
version = "1.0.0-dev"
edition = "2021"



[dependencies]
# Arkworks
ark-bw6-761 = { version = "0.4.0", default-features = false }
ark-ec = { version = "0.4.0", default-features = false }
ark-ff = { version = "0.4.0", default-features = false }
ark-std = { version = "0.4.0", default-features = false }

# Frontier
fp-evm = { version = "3.0.0-dev", path = "../../../../evm-primitives/evm", default-features = false }

[dev-dependencies]
# Frontier
pallet-evm-test-vector-support = { version = "1.0.0-dev", path = "../../test-vector-support",default-features = false }

[features]
default = ["std"]
std = [
	# Arkworks
	"ark-bw6-761/std",
	"ark-ec/std",
	"ark-ff/std",
	"ark-std/std",

	# Frontier
	"fp-evm/std",
]
