[package]
name = "remote-ext-tests-bags-list"
publish = false
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
saitama-runtime = { path = "../../../runtime/saitachain" }
saitama-runtime-constants = { path = "../../../runtime/saitachain/constants" }

pallet-bags-list-remote-tests = { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev" }
sp-tracing =  { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev" }
frame-system =  { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev" }
sp-core =  { git = "ssh://git@github.com/saitamahub/Saita-substrate.git" , branch = "dev" }

clap = { version = "4.4.2", features = ["derive"] }
log = "0.4.17"
tokio = { version = "1.24.2", features = ["macros"] }
