[package]
name = "saitama-node-core-pvf-common"
description = "SaitaChain crate that contains functionality related to PVFs that is shared by the PVF host and the PVF workers."
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cpu-time = "1.0.0"
futures = "0.3.21"
gum = { package = "tracing-gum", path = "../../../gum" }
libc = "0.2.139"
tokio = { version = "1.24.2", features = ["fs", "process", "io-util"] }

parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }

saitachain-parachain-primitives = { path = "../../../../parachain" }
saitama-primitives = { path = "../../../../primitives" }

sc-executor = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sc-executor-common = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sc-executor-wasmtime = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }

sp-core = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sp-externalities = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sp-io = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }
sp-tracing = {  git = "ssh://git@github.com/saitamahub/Saita-substrate.git", branch = "dev" }

[target.'cfg(target_os = "linux")'.dependencies]
landlock = "0.2.0"

[dev-dependencies]
assert_matches = "1.4.0"
tempfile = "3.3.0"

[features]
# This feature is used to export test code to other crates without putting it in the production build.
# Also used for building the puppet worker.
test-utils = []
jemalloc-allocator = []
